apps/first_draft/urls.py
from django.conf.urls import url
from .views import index


urlpatterns = [
    url(r'^$', index, name='index')
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Project apps
    url(r'^first-draft/', include('apps.first_draft.urls', namespace='first-draft')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

apps/first_draft/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
import pytz

# from apps.locations.models import Planet
# from apps.economy.models import Resource


LOCATIONS = (
    (0, 'planetary surface'),
    (1, 'moon surface')
)


# class Building(models.Model):
#     name = models.CharField(max_length=255, unique=True)
#     image = models.ImageField(upload_to='buildings', null=True, blank=True)
#     base_cost_metal = models.PositiveIntegerField(default=0)
#     base_cost_crystal = models.PositiveIntegerField(default=0)
#     base_cost_deuter = models.PositiveIntegerField(default=0)
#     base_energy_use = models.PositiveIntegerField(default=0)
#
#     def __str__(self):
#         return self.name

apps/structures/models.py
import pytz
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone

from apps.locations.models import Planet


class Building(models.Model):
    name = models.CharField(max_length=255, unique=True)
    image = models.ImageField(upload_to='buildings', null=True, blank=True)
    base_cost_metal = models.PositiveIntegerField(default=0)
    base_cost_crystal = models.PositiveIntegerField(default=0)
    base_cost_deuter = models.PositiveIntegerField(default=0)
    base_energy_use = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class PlayerBuilding(models.Model):
    LOCATIONS = (
        (0, 'planetary surface'),
        (1, 'moon surface')
    )

    building = models.ForeignKey(Building)
    planet = models.ForeignKey(Planet, related_name='buildings')
    building_location = models.IntegerField(choices=LOCATIONS, default=0)
    current_level = models.PositiveIntegerField(default=0)
    new_level = models.PositiveIntegerField(null=True, blank=True)  # to update resource amount before building level
    upgrade_started_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['planet', 'building_location', 'building']

    def __str__(self):
        return '{}:{}:{}'.format(self.pk, self.building_location, self.building)

    def is_upgrading(self):
        if self.upgrade_started_at and self.upgrade_ends_at():
            return self.upgrade_started_at <= timezone.datetime.now(tz=pytz.UTC) <= self.upgrade_ends_at()

    def upgrade_time(self):
        """
        How long it take to upgrade building to the next level
        """
        uni_speed = float(self.planet.owner.universe.acceleration)
        lvl = self.current_level or 1
        metal_cost = self.building.base_cost_metal * 1.5**lvl
        crystal_cost = self.building.base_cost_crystal * 1.5**lvl
        rf = 0  # robotic factory
        nf = 0  # nanite factory

        upgrade_time = (metal_cost * crystal_cost) / (2500 * (1 + rf) * 2**nf * uni_speed)

        print(upgrade_time)

        return upgrade_time

    def upgrade_ends_at(self):
        upgrade_time = self.upgrade_time()
        upgrade_started = self.upgrade_started_at
        if upgrade_started:
            upgrade_ends_at = upgrade_started + timezone.timedelta(seconds=upgrade_time)
            if upgrade_ends_at >= timezone.datetime.now(tz=pytz.UTC):
                return upgrade_ends_at
            else:
                self.current_level += 1
                self.upgrade_started_at = None
                self.save()
        return None


# class Defense(models):
#     pass


# class PlayerDefense(models):
#     pass


@receiver(pre_save, sender=PlayerBuilding)
def save_resource_state_on_building_update(sender, instance, *args, **kwargs):
    from apps.economy.models import Resource

    building_id = instance.building.id
    current_level = instance.current_level
    new_level = instance.new_level

    # If building's level was changed, first save the resource it generated
    # to prevent wrong recalculation of "accumulated" value,
    # that uses "produced_per_hour" coefficient dependant on building's level
    if current_level != new_level and new_level:
        if building_id in [1, 2, 3]:
            resource = Resource.objects.get(
                resource_type=building_id,
                planet=instance.planet,
                location=instance.building_location,
            )
            resource.save()
        instance.current_level = new_level
        instance.new_level = None

apps/first_draft/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from apps.structures.models import PlayerBuilding
from apps.economy.models import Resource


def index(request):
    first_building = PlayerBuilding.objects.filter(planet=1)[0]
    metal = Resource.objects.get(planet=1, resource_type=1)
    crystal = Resource.objects.get(planet=1, resource_type=2)
    deuterium = Resource.objects.get(planet=1, resource_type=3)

    upgrade_starts_at = first_building.upgrade_started_at
    if upgrade_starts_at:
        upgrade_starts_at = upgrade_starts_at.timestamp()

    upgrade_ends_at = first_building.upgrade_ends_at()
    upgraded_percent = 100
    one_percent = first_building.upgrade_time() / 100
    if upgrade_ends_at:
        upgrade_ends_at = upgrade_ends_at.timestamp()
        upgraded_percent = 100 - round((upgrade_ends_at - timezone.now().timestamp()) / one_percent, 1)


    context = {
        'building': first_building,
        'upgrade_started_at': upgrade_starts_at,
        'upgrade_ends_at': upgrade_ends_at,
        'upgraded_percent': upgraded_percent,
        'metal': metal,
        'crystal': crystal,
        'deuterium': deuterium
    }

    return render(request, 'first_draft/index.html', context)


# def cancel_building_upgrade(request):
#     redirect

apps/first_draft/templates/first_draft/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Title</title>
</head>
<body>
    <h1>
        Location: {{ building.planet.planet_name }} ({{ building.get_building_location_display }})
    </h1>
    <p>
        Planet's surface: {{ building.planet.surface }}/{{ building.planet.free_surface }}
    </p>

    <p>
        [ metal:
        <span
            {% if metal.reached_max_capacity %}
            class="capacity_exceeded"
            {% else %}
            class="capacity_not_exceeded"
            {% endif %}>
            {{ metal.amount|add:metal.accumulated }}
        </span>
        ({{ metal.production_speed }}) ]
        [ crystal:
        <span
            {% if crystal.reached_max_capacity %}
            class="capacity_exceeded"
            {% else %}
            class="capacity_not_exceeded"
            {% endif %}>
            {{ crystal.amount|add:crystal.accumulated }}
        </span>
        ({{ crystal.production_speed }}) ]
        [ deuter:
        <span
            {% if deuter.reached_max_capacity %}
            class="capacity_exceeded"
            {% else %}
            class="capacity_not_exceeded"
            {% endif %}>
            {{ deuterium.amount|add:deuterium.accumulated }}
        </span>
        ({{ deuterium.production_speed }}) ]
    </p>

    <h3>First building</h3>
    <img src="{{ building.building.image.url }}" alt="" class="src">
    <ul>
        <li>Building: {{ building.id }}. {{ building.building.name }}</li>
        <li>Owner: {{ building.planet.owner }}</li>
        <li>
            <p>
                Mine lvl: {{ building.current_level }}
            </p>

            <span id="timer"
                  data-upgrade-started-at="{{ upgrade_started_at }}"
                  data-upgrade-ends-at="{{ upgrade_ends_at }}"
                  data-upgraded-percent="{{ upgraded_percent }}">
            </span>

            {% if building.is_upgrading %}
            <p>
                <span style="font-weight: 700;">(Upgrading) </span>
                <span id="foo"></span>
            </p>

            <div class="progress" style="width: 200px; height: 15px;">
              <div id="dynamic-progress-bar" class="progress-bar"
                   role="progressbar"
                   style="width: 0%;"
                   aria-valuenow="0"
                   aria-valuemin="0"
                   aria-valuemax="100">
                  0%
              </div>
            </div>
            {% endif %}
        </li>
    </ul>

    {% if building.is_upgrading %}
    <button>Cancel upgrade</button>
    {% else %}
    <button>Upgrade</button>
    <button>Downgrade</button>
    {% endif %}

    <!-- jQuery CDN -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

    <script src="{% static 'js/timer.js' %}"></script>
</body>
</html>